### ISSUE TITLE
adapt the configuration file changes for `cess-miner`

### ISSUE THREAD

**Issue by 0xbillw** [CESSProject/config-gen#28]
## The reason for the changes:
- Due to configuration changes in the upstream 'cess-miner' due to the issue: CESSProject/cess-miner#289

## Config sample
```yaml
app:
  # workspace
  workspace: "/"
  # communication port
  port: 4001
  # maximum space used, the unit is GiB
  maxusespace: 2000
  # number of cpus used, 0 means use all
  cores: 0

chain:
  # signature account mnemonic
  mnemonic: "" 
  # staking account
  # if you fill in the staking account, the staking will be paid by the staking account,
  # otherwise the staking will be paid by the signature account.
  stakingacc: ""
  # earnings account
  earningsacc: ""
  # timeout for waiting for transaction packaging, default 12 seconds
  timeout: 12
  # rpc address list
  rpcs:
    - "wss://testnet-rpc.cess.cloud/ws/"
  # priority tee address list
  tees:
```
